name: Protobuf Generation Workflow

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: '0'
      
      - uses: actions/setup-go@v6
        with:
          go-version: '^1.24.4'
          cache: true
      
      - name: Check Go version
        run: go version

      - uses: bufbuild/buf-action@v1
        name : Setup Buf CLI
        with:
          version: 1.59.0
          # Include this line if you only want to set up the Action and do nothing else.
          setup_only: true
          # Include a GitHub token to ensure API requests aren't rate limited.
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate Protobuf code
        run: | 
          make clear-protogen
          make generate-proto

      - name: Install dependencies
        run: make install-deps

    
      - name: Check for changes openapiv2
        id: git-check-openapiv2
        run: echo "changed=$(if git status --porcelain | grep -q 'openapiv2/'; then echo true; else echo false; fi)" >> $GITHUB_OUTPUT
        
      - if: steps.git-check-openapiv2.outputs.changed == 'true'
        name: Commit generated files
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          file_pattern: 'openapiv2/*'
          commit_message: "ci(openapiv2): auto-generate openapiv2 files skipping CI [skip ci]"

      - name: Check for changes 
        id: git-check
        run: echo "changed=$(if git status --porcelain | grep -q 'protogen/'; then echo true; else echo false; fi)" >> $GITHUB_OUTPUT

      - if: steps.git-check.outputs.changed == 'true'
        name: Commit generated files
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          file_pattern: 'protogen/* openapiv2/*'
          commit_message: "ci(proto): auto-generate protobuf files skipping CI [skip ci]"

      - if: steps.git-check.outputs.changed == 'true' || steps.git-check-openapiv2.outputs.changed == 'true'
        name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        id: tag_version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_PREFIX: v
          DEFAULT_BUMP: ${{ steps.git-check-openapiv2.outputs.changed == 'true' && 'minor' || 'patch' }}
          
      - name: Get the created tag
        if: steps.git-check.outputs.changed == 'true' || steps.git-check-openapiv2.outputs.changed == 'true'
        run: "echo Tag Version: ${{ steps.tag_version.outputs.new_tag }}"